services:
  
  pokedex.api:
    build:
      context: .
      dockerfile: src/Pokedex.API/Dockerfile
    container_name: pokedex-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=pokedex.db;Port=5432;Database=pokedex;Username=professor;Password=oak123
      - Jwt__Key=your-super-secret-key-make-this-long-and-random
      - Jwt__Issuer=PokedexAPI
      - Jwt__Audience=PokedexClient
      - Jwt__ExpiryInMinutes=60
    depends_on:
      pokedex.db:
        condition: service_healthy
    restart: unless-stopped
    
  pokedex.db:
    image: postgres:18-alpine
    container_name: pokedex-db
    environment:
      POSTGRES_DB: pokemon
      POSTGRES_USER: professor
      POSTGRES_PASSWORD: oak123
    ports:
      - "5432:5432"
    volumes:
      - pokedex-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U professor -d pokedex"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
      
volumes:
  pokedex-data: