// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pokedex.Infrastructure.Data;

#nullable disable

namespace Pokedex.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PokedexDbContext))]
    [Migration("20260615071034_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pokedex.Domain.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("HeightInMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("integer");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A strange seed was planted on its back at birth.",
                            HeightInMeters = 0.69999999999999996,
                            Name = "Bulbasaur",
                            PokedexNumber = 1,
                            WeightInKg = 6.9000000000000004
                        },
                        new
                        {
                            Id = 2,
                            Description = "The flame at the tip of its tail makes a sound as it burns.",
                            HeightInMeters = 0.59999999999999998,
                            Name = "Charmander",
                            PokedexNumber = 4,
                            WeightInKg = 8.5
                        },
                        new
                        {
                            Id = 3,
                            Description = "After birth, its back swells and hardens into a shell.",
                            HeightInMeters = 0.5,
                            Name = "Squirtle",
                            PokedexNumber = 7,
                            WeightInKg = 9.0
                        });
                });

            modelBuilder.Entity("Pokedex.Domain.Entities.PokemonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PokemonId = 1,
                            TypeName = "Grass"
                        },
                        new
                        {
                            Id = 2,
                            PokemonId = 1,
                            TypeName = "Poison"
                        },
                        new
                        {
                            Id = 3,
                            PokemonId = 2,
                            TypeName = "Fire"
                        },
                        new
                        {
                            Id = 4,
                            PokemonId = 3,
                            TypeName = "Water"
                        });
                });

            modelBuilder.Entity("Pokedex.Domain.Entities.PokemonType", b =>
                {
                    b.HasOne("Pokedex.Domain.Entities.Pokemon", "Pokemon")
                        .WithMany("Types")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Pokedex.Domain.Entities.Pokemon", b =>
                {
                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
