### Register a new trainer
POST https://localhost:7020/api/auth/register
Content-Type: application/json

{
  "username": "Ash",
  "email": "ash@pallet.town",
  "password": "Pikachu1@"
}

### Login
POST https://localhost:7020/api/auth/login
Content-Type: application/json

{
  "email": "ash@pallet.town",
  "password": "Pikachu1@"
}

### Add a Pokémon (protected — paste your token below!)
POST https://localhost:7020/api/pokemon
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjVmOGJkMGFlLTIwZmEtNGUwNy05ZGZjLWY0OWRlM2M4YjcyNCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJBc2giLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhc2hAcGFsbGV0LnRvd24iLCJqdGkiOiJmZGQ3NWMyZC1jMTA4LTQ4YjctOGZhYy0xYzEwOGJiN2FlN2QiLCJleHAiOjE3ODE1Mjk5OTIsImlzcyI6IlBva2VkZXhBUEkiLCJhdWQiOiJQb2tlZGV4Q2xpZW50In0.5Nx31RVcuTM59naqFV_ZekLEdxiqD9Fbyw88ZD9ctvM

{
  "pokedexNumber": 25,
  "name": "Pikachu",
  "description": "Stores electricity in its cheeks.",
  "heightInMeters": 0.4,
  "weightInKg": 6.0,
  "types": ["Electric"]
}